version: "3.9"
services:
  redis:
    image: redis:7-alpine
    restart: always

  elastic:
    image: elasticsearch:7.17.13
    restart: always
    environment: 
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - elastic:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  
  wp-fpm:
    image: wordpress:6-fpm
    restart: always
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    ports:
      - "9000:9000"
    volumes:
      - html:/var/www/html
      - ./conf/php_optional.ini:/usr/local/etc/php/conf.d/php_optional.ini
    env_file:
      - ./conf/wordpress.env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  db:
    image: mariadb:11-jammy
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - ./conf/db.env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

volumes:
  html:
    driver: local
    driver_opts:
      type: none
      device: $PWD/html 
      o: bind
  dbdata:
  elastic:
    driver: local
